### ISSUE TITLE
[Firebase Messaging] Not receiving notifications on Flutter ^1.9 in release mode

### ISSUE THREAD

**Issue by apaolino** [FirebaseExtended/flutterfire#140]
I upgraded to Flutter 1.9 from 1.7.8 then my notifications stopped working (the only thing I saw in the logs was: "MyFirebaseMsgService  From: <some number>" when notifications arrived).

So I downgraded to 1.7.8 and they started to work again.

Using firebase_messaging 5.1.5.

**To Reproduce**
-Install Flutter 1.9 
-Receive a firebase notification
-Any callback method is fired

**Expected behavior**
-Callbacks fired

**Comment by Mooibroek** [comment]
Apparently having the same issue. Only on iOS tho. Push still works on Android.

**Comment by nhwilly** [comment]
Anyone have something that works? I've spent an entire week fighting this.

IOS gives me no notifications if the app isn't running. Simulator or device. Android seems to work, so far.

Ios message is delivered via "onmessage" when app resumes.

Constantly getting "device type is null" from one session to the next.

Incredibly frustrating.

**Comment by apaolino** [comment]
Unfortunately I had to downgrade to flutter 1.7.8. 
Waiting for news

**Comment by apaolino** [comment]
Resolved upgrading to Flutter 1.10.7 beta

**Comment by BondarenkoStas** [comment]
Good, than I think it's safe to close the issue. If beta still won't work, please comment, I will re-open it right away.

**Comment by apaolino** [comment]
I've just discovered that in release mode it doesn't work. I've downgraded to 1.7.8 to get it work. 
How can we resolve please? Notifications are so important in our app

**Comment by kroikie** [comment]
@apaolino Are you seeing this for iOS only or both iOS and Android?

**Comment by kroikie** [comment]
This seems to be a dup of https://github.com/FirebaseExtended/flutterfire/issues/1056

@apaolino Please provide your response [here](https://github.com/FirebaseExtended/flutterfire/issues/1056)

**Comment by apaolino** [comment]
It's for Android. The strange thing is that changing the version of Flutter with one > 10 it worked in debug mode but not in release mode. And the code was unchanged.

**Comment by apaolino** [comment]
Tried with last stable Flutter (1.12.13+hotfix5) and notifications work in debug mode but not in release.
I don't understand why it happens. I'm still locked on Flutter 1.7.8 because of this problem.

Don't know if it could be a problem on my side but I've created a parent widget, that I never dispose, and in which there are firebase messaging callbacks onResume, onMessage and so on..
Under this widget there are all other widgets. This in order to receive notifications and redirect to child widgets in every moment of app execution.
