### ISSUE TITLE
[firebase_app_check] App Check token not accessible in Xcode console (v0.4.1)

### ISSUE THREAD

**Issue by tyypgzl** [FirebaseExtended/flutterfire#17778]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

iOS

### Description

After updating to firebase_app_check v0.4.1, I can no longer access or print the App Check token from the Xcode console.
It seems that there were some changes introduced in PR #17723, which might have modified the usage pattern for retrieving tokens. However, until the old usage is fully deprecated, it should ideally remain supported to avoid breaking existing implementations.

Additionally, the AppleAppAttestProvider class from the firebase_app_check_platform_interface package is not exported in firebase_app_check package.
path: `packages/firebase_app_check/firebase_app_check/lib/firebase_app_check.dart`

### Reproducing the issue

1.	Update to firebase_app_check: 0.4.1
2.	Run the iOS app and attempt to log or fetch the App Check token from Xcode console
3.	Observe that the token is no longer accessible

### Firebase Core version

4.1.0

### Flutter Version

3.35.3

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.9.2
Flutter SDK 3.35.3
sfxlab 1.0.1+6

dependencies:
- adapty_flutter 3.11.2 [flutter meta]
- analytics 1.0.0 [flutter firebase_analytics]
- app_info 1.0.0 [flutter device_info_plus package_info_plus]
- audioplayers 6.5.1 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- auto_size_text 3.0.0 [flutter]
- carousel_slider 5.1.1 [flutter]
- cloud_firestore 6.0.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 6.0.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.19.1
- equatable 2.0.7 [collection meta]
- external_path 2.2.0 [flutter plugin_platform_interface]
- firebase_analytics 12.0.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.4.0+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 6.0.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 4.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 5.0.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 16.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flag 7.0.1 [flutter flutter_svg enum_to_string]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_hooks 0.21.3+1 [flutter]
- flutter_localizations 0.0.0 [flutter intl path]
- flutter_native_splash 2.4.6 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_riverpod 3.0.0 [collection flutter flutter_test meta riverpod state_notifier]
- force_update 1.0.0 [flutter equatable pub_semver url_launcher firebase_remote_config ui]
- go_router 16.2.1 [collection flutter flutter_web_plugins logging meta]
- go_router_paths 0.2.2
- google_sign_in 7.1.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hooks_riverpod 3.0.0 [collection flutter flutter_hooks flutter_riverpod flutter_test riverpod state_notifier]
- http 1.5.0 [async http_parser meta web]
- path 1.9.1
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 12.0.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- review 1.0.0 [flutter in_app_review]
- scrollable_positioned_list 0.3.8 [flutter collection]
- share 1.0.0 [flutter share_plus]
- share_plus 12.0.0 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- skeletonizer 2.1.0+1 [flutter]
- slide_countdown 2.0.3-dev.2 [flutter pausable_timer]
- smooth_page_indicator 1.2.1 [flutter]
- storage 1.0.0 [flutter shared_preferences flutter_secure_storage]
- text_gradiate 1.0.1 [flutter]
- ui 1.0.0 [flutter font_awesome_flutter lucide_icons_flutter gap lottie cached_network_image syncfusion_flutter_sliders flutter_svg webview_flutter webview_flutter_wkwebview webview_flutter_android]
- uuid 4.5.1 [crypto sprintf meta fixnum]

dev dependencies:
- build_runner 2.7.1 [args async build build_config build_daemon build_runner_core built_collection code_builder crypto dart_style frontend_server_client glob graphs http_multi_server io logging meta mime path pub_semver shelf shelf_web_socket stack_trace stream_transform watcher web_socket_channel yaml]
- flutter_gen_runner 5.11.0 [flutter_gen_core build collection crypto glob path yaml]
- lint 1.0.0
- melos 6.3.3 [ansi_styles args async cli_launcher cli_util collection conventional_commit file glob graphs http meta mustache_template path platform pool prompts pub_semver pub_updater pubspec_parse string_scanner yaml yaml_edit]

transitive dependencies:
- _fe_analyzer_shared 85.0.0 [meta]
- _flutterfire_internals 1.3.61 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.7.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansi_styles 0.3.2+1
- ansicolor 2.0.3
- archive 4.0.7 [crypto path posix]
- args 2.7.0
- async 2.13.0 [collection meta]
- audioplayers_android 5.2.1 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.3.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.2.1 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.1.1 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.1.1 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.2.1 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 3.1.0 [analyzer async build_runner_core convert crypto glob logging package_config path]
- build_config 1.2.0 [checked_yaml json_annotation path pubspec_parse]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 3.0.3 [analyzer async build build_runner_core collection package_config path pool pub_semver]
- build_runner_core 9.3.1 [analyzer async build build_config build_resolvers build_runner built_collection built_value collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.12.0 [built_collection collection fixnum meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- charcode 1.4.0
- checked_yaml 2.0.4 [json_annotation source_span yaml]
- cli_config 0.2.0 [args yaml]
- cli_launcher 0.3.2+1 [path yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.2
- cloud_firestore_platform_interface 7.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 5.0.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.8.4 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 5.0.1 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- code_builder 4.11.0 [built_collection built_value collection matcher meta]
- color 3.0.0
- conventional_commit 0.6.1+1
- convert 3.1.2 [typed_data]
- coverage 1.15.0 [args cli_config glob logging meta package_config path source_maps stack_trace vm_service yaml]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dart_style 3.1.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dartx 1.2.0 [characters collection crypto meta path time]
- device_info_plus 12.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.3 [flutter meta plugin_platform_interface]
- enum_to_string 2.2.1
- fake_async 1.3.3 [clock collection]
- ffi 2.1.4
- file 7.0.1 [meta path]
- firebase_analytics_platform_interface 5.0.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.6.0+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_check_platform_interface 0.2.0+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+16 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 8.1.1 [_flutterfire_internals collection firebase_core flutter http meta plugin_platform_interface]
- firebase_auth_web 6.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 6.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 3.1.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.12 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.7.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 4.0.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config 6.0.1 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_remote_config_platform_interface 2.0.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.11 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_gen_core 5.11.0 [meta path yaml mime xml dartx color collection json_annotation glob logging dart_style archive args pub_semver vector_graphics_compiler image_size_getter image]
- flutter_secure_storage 9.2.4 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.2.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_svg 2.2.1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing collection meta stream_channel]
- flutter_web_plugins 0.0.0 [flutter]
- font_awesome_flutter 10.10.0 [flutter]
- frontend_server_client 4.0.0 [async path]
- gap 3.0.1 [flutter]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3+1 [meta web]
- google_sign_in_android 7.0.5 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 6.1.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 3.1.0 [flutter plugin_platform_interface]
- google_sign_in_web 1.0.0 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.2 [collection]
- hashcodes 2.0.0
- html 0.15.6 [csslib source_span]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.4 [archive meta xml]
- image_size_getter 2.4.1 [collection hashcodes meta]
- in_app_review 2.0.11 [flutter in_app_review_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- intl 0.20.2 [clock meta path]
- io 1.0.5 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 11.0.2 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.10 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.2 [leak_tracker matcher meta]
- logging 1.3.0
- lottie 3.3.2 [archive flutter http path vector_math]
- lucide_icons_flutter 3.1.0 [flutter]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- mustache_template 2.0.1
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus 9.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.2.1 [flutter meta plugin_platform_interface]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.18 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pausable_timer 3.1.0+3 [clock]
- permission_handler_android 13.0.1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.7 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.3.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 7.0.1 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- posix 6.0.3 [ffi meta path]
- process 5.0.5 [file path platform]
- prompts 2.0.0 [charcode io]
- pub_semver 2.2.0 [collection]
- pub_updater 0.5.0 [http json_annotation process pub_semver]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod 3.0.0 [async clock collection meta state_notifier test]
- rxdart 0.28.0
- share_plus_platform_interface 6.1.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.4.12 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.2+2 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.6 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- syncfusion_flutter_core 31.1.21 [flutter vector_math]
- syncfusion_flutter_sliders 31.1.21 [flutter intl syncfusion_flutter_core]
- synchronized 3.4.0
- term_glyph 1.2.2
- test 1.26.2 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.7.6 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.11 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- time 2.1.5 [clock]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.3.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.21 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.3 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.19 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.19 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.2.0
- vm_service 15.0.2
- watcher 1.1.3 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- webkit_inspection_protocol 1.2.1 [logging]
- webview_flutter 4.13.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 4.10.2 [flutter meta webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.14.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.23.0 [flutter meta path webview_flutter_platform_interface]
- win32 5.14.0 [ffi]
- win32_registry 2.1.0 [ffi meta win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.6.1 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]
- yaml_edit 2.2.2 [collection meta source_span yaml]

```

</details>

**Comment by SelaseKay** [comment]
Hi @tyypgzl, thanks for reporting this. The issue has been fixed in https://github.com/firebase/flutterfire/pull/17742
 and the fix will be available in the next release.

**Comment by tyypgzl** [comment]
Hi @SelaseKay , thanks for the quick response, However, the second topic is still not addressed:

the AppleAppAttestProvider class from the firebase_app_check_platform_interface package is not exported in firebase_app_check package.
path: `packages/firebase_app_check/firebase_app_check/lib/firebase_app_check.dart`

**Comment by SelaseKay** [comment]
Hi @tyypgzl, https://github.com/firebase/flutterfire/pull/17740 resolves that.
