### ISSUE TITLE
[FireBase Messaging] iOS only receiving messages in foreground aka. onResume and onLaunch not executing

### ISSUE THREAD

**Issue by dazednconfusing** [FirebaseExtended/flutterfire#1799]
**Describe the bug**
I followed all the instructions in the ios integration instructions on the read me and I am able to receive messages from the firebase console but only when the flutter app is running in the foreground. I am testing this with an iphone 11 max simulator. I set push notifcations on in capabilities as well as  background fetch, remote notifications, background processing on in the background modes capabilities.

**To Reproduce**
1. Create a widget that instantiates a new firebase message handler, asks for permission, and configures the onMessage, onResume, onLaunch methods and prints the device token.

2. display this widget in the main.dart file

3. Run a simulator with flutter run and exit the app and go to the home page 

4. Go to your firebase messaging console and send a message to the printed device token

**Expected behavior**
I expect to see a notification banner with the message sent from firebase. NOTE ** If the app is open then onMessage method runs fine and a snackbar widget is displayed as desired.

**Additional context**
None I can think of

**Comment by Theunodb** [comment]
PS. You cant receive notifications on the iOS simulator when you have the app closed. You need to test this on a physical device.

**Comment by dazednconfusing** [comment]
Even with a physical device the notifications never came through.

Is Firebase messaging simply unable to send push notifications in the background or when the app is closed for iOS 13?

**Comment by iapicca** [comment]
Hi @dazednconfusing 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/1590)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by dazednconfusing** [comment]
The issue you linked to has only a solution for android whereas this is for ios. Additionally, I have found that notifications are not received in the foreground when run through xcode but they are received when run with flutter

**Comment by acoutts** [comment]
I'm having this issue as well.

**Comment by gdagitrep** [comment]
@dazednconfusing , @acoutts Did you find a solution, I am on a similar boat?

**Comment by acoutts** [comment]
No solution yet..

**Comment by krishnakumarcn** [comment]
Still facing the issue. Any solutions?

**Comment by SamerDiab** [comment]
+1, I receive the notification in the foreground but not in the background although I implemented accordingly to the documentation.

**Comment by campioncino** [comment]
I still have the same issue.
No solution so far?

Any suggestion will be appreciated

**Comment by bougsid** [comment]
Still waiting for any suggestions or fix

**Comment by YudiTan** [comment]
facing the same issue -- push notification only received for onMessage but not for the other callbacks (i.e. doesnt work when app is in background / closed)

**Comment by misaelriojasftf** [comment]
that's it! moving to one signal

**Comment by gdagitrep** [comment]
**acoutts** posted a solution somewhere to disable  remote debugging. That solution worked for me on a real device. Earlier it only worked with app in foreground.

**Comment by misaelriojasftf** [comment]
where is this solution

**Comment by misaelriojasftf** [comment]
it WORKED! OMG FCM don't work on simulators or even if you try plugging your device and making profile, debug, release.... nothing will work until you send a build to Testflight. that's so bad but at least works !

**Comment by AyooshAgarwal** [comment]
> it WORKED! OMG FCM don't work on simulators or even if you try plugging your device and making profile, debug, release.... nothing will work until you send a build to Testflight. that's so bad but at least works !

This works  but in the opposite way,
 now onLaunch and onResume callback are working [through Testflight], but onMessage callback is not getting fired. 
On the other hand when I was testing with a plugged in device  , it was the other way round i.e notification were only showing up when the app was in foreground and only onMessage callback was fired , when app was in background/terminated no notifications were showing up in the system tray (thus no way to fire onLaunch/onResume callbacks).

Any suggestions ?

**Comment by kaarens93** [comment]
also having this issue

**Comment by Fatimamostafa** [comment]
> **acoutts** posted a solution somewhere to disable remote debugging. That solution worked for me on a real device. Earlier it only worked with app in foreground.

Which solution was that? I'm currently stuck on this.

**Comment by gdagitrep** [comment]
> > **acoutts** posted a solution somewhere to disable remote debugging. That solution worked for me on a real device. Earlier it only worked with app in foreground.
> 
> Which solution was that? I'm currently stuck on this.

To disable remote debugging; basically uncheck the "Connect via network" box on Device and Simulator window of XCode. This [link](https://dev.to/rickey_oak/ios-remote-debugging---a-how-to-guide-2onh) can help.

**Comment by Codepeaker** [comment]
> it WORKED! OMG FCM don't work on simulators or even if you try plugging your device and making profile, debug, release.... nothing will work until you send a build to Testflight. that's so bad but at least works !



> it WORKED! OMG FCM don't work on simulators or even if you try plugging your device and making profile, debug, release.... nothing will work until you send a build to Testflight. that's so bad but at least works !

Does that really work for anybody else

**Comment by acoutts** [comment]
> > it WORKED! OMG FCM don't work on simulators or even if you try plugging your device and making profile, debug, release.... nothing will work until you send a build to Testflight. that's so bad but at least works !
> 
> Does that really work for anybody else

No it will work if you plug in a phone and build locally for it. Simulators will not receive pushes will receive data messages. They will still get notifications sent to FCM but they come through as a data message and will have the notification data the same as a real device. The best way to test is with a physical phone.

**Comment by jkz27** [comment]
@acoutts by testing with a physical device do you mean to build the app on a physical device through Xcode or submit it to test flight? It is working completely fine for me on android, and on IOS I followed the steps of requesting permissions and setup but I am receiving nothing on the background/quit state, even though I build it through Xcode on a physical device

**Comment by Ehesp** [comment]
As long as the app is running on a physical device it's fine, whether it's a debug/prod build or not. It just needs to be on a physical one.

We did mention this in the new docs:

![image](https://user-images.githubusercontent.com/842078/104900427-f7e4a500-5973-11eb-81d2-4e870787c3df.png)

I'd also suggest upgrading to v8 if possible.

**Comment by russellwheatley** [comment]
Hey @dazednconfusing, do you mind upgrading to the latest version: `9.1.2`, trying on a physical device and updating this thread? thanks.

**Comment by icodeyou** [comment]
I have the same problem, even with my physical device.

**Comment by russellwheatley** [comment]
Due to lack of response from OP combined with a number of major release version iterations and much more detailed docs regarding [ios messaging setup](https://firebase.flutter.dev/docs/messaging/usage). I'm going to close this issue and ask any that any new problems with the current version be created as a new issue.
