### ISSUE TITLE
[cloud_function] No implementation found for method CloudFunctions#call

### ISSUE THREAD

**Issue by Jbz797** [FirebaseExtended/flutterfire#1866]
### Describe the bug
Since the last update i have this error when a try to call a cloud function
```
MissingPluginException (MissingPluginException(No implementation found for method CloudFunctions#call on channel plugins.flutter.io/cloud_functions))
```

### The code snippet
```
Future<dynamic> forgotPassword(Map<String, dynamic> values) async {
  try {
    final response = await CloudFunctions.instance.getHttpsCallable(functionName: 'forgotPassword').call({
      'id': values['id'],
      'lang': values['lang'],
      'role': 'installer'
    });
    return response.data;
  } catch (e) {
    return {
      'message': e.message
    };
  }
}
```

### Flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/jeaden/flutter
    • Framework revision 27321ebbad (il y a 6 semaines), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jeaden/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • WAS LX1A • H3XDU17B07001643 • android-arm64 • Android 8.0.0 (API 26)

**Comment by bhanuka96** [comment]
same.. do you find any solution?

**Comment by mark-veenstra** [comment]
Same here since the last version, but last version is needed since it should fix the DEADLINE_EXCEEDED error.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method CloudFunctions#call on channel plugins.flutter.io/cloud_functions)`

**Comment by Jbz797** [comment]
No, I went backwards in time. But it's a pity because this update is interesting for me because it fixes the timeout problem on Android.

**Comment by Jbz797** [comment]
I've been waiting a month for this update :(

**Comment by mark-veenstra** [comment]
Could it be that we need to call the function differently? Since this update a second package is installed also named `cloud_functions_platform_interface`. But if the API changed it shouldn't be a hotfix release

**Comment by Jbz797** [comment]
Yes, I saw that the interface has changed, so I don't really understand.

**Comment by bhanuka96** [comment]
temporary solution: change  ` cloud_functions: ^0.4.1+7 to cloud_functions: 0.4.1+6`. remember don't add `^` this mark

**Comment by Jbz797** [comment]
No because if i do that i have the DEADLINE_EXCEEDED bug inherent to the previous update.

**Comment by bhanuka96** [comment]
> No because if i do that i have the DEADLINE_EXCEEDED bug inherent to the previous update.

delete manually cloud_functions 0.4.1+7 (in flutter installation)project and then install

**Comment by mark-veenstra** [comment]
> > No because if i do that i have the DEADLINE_EXCEEDED bug inherent to the previous update.
> 
> delete manually cloud_functions 0.4.1+7 (in flutter installation)[ android studio > external ibraries > Dart Packages > right click on cloud_functions 0.4.1+7] > go to finder > and delete it] project and then install

@bhanuka96 Not sure what that would solve? The +7 release still would throw same error. Downgrading to +6 release brings back the DEADLINE_EXCEEDED error on Android.

**Comment by bhanuka96** [comment]
> > > No because if i do that i have the DEADLINE_EXCEEDED bug inherent to the previous update.
> > 
> > 
> > delete manually cloud_functions 0.4.1+7 (in flutter installation)[ android studio > external ibraries > Dart Packages > right click on cloud_functions 0.4.1+7] > go to finder > and delete it] project and then install
> 
> @bhanuka96 Not sure what that would solve? The +7 release still would throw same error. Downgrading to +6 release brings back the DEADLINE_EXCEEDED error on Android.

don't use ^ mark... do you delete cloud_functions 0.4.1+7 from Flutter packages path?

**Comment by mark-veenstra** [comment]
If I even try this implementation from the API docs: https://pub.dev/documentation/cloud_functions/latest/cloud_functions/HttpsCallable/call.html the error still occurs

**Comment by bhanuka96** [comment]
> If I even try this implementation from the API docs: https://pub.dev/documentation/cloud_functions/latest/cloud_functions/HttpsCallable/call.html the error still occurs

for me it's working..  I deleted +7 project and other new cloud function project and then  install`cloud_functions: 0.4.1+7`

**Comment by mark-veenstra** [comment]
> > If I even try this implementation from the API docs: https://pub.dev/documentation/cloud_functions/latest/cloud_functions/HttpsCallable/call.html the error still occurs
> 
> for me it's working.. I deleted +7 project and other new cloud function project and then install`cloud_functions: 0.4.1+7`

Does not work. +7 still gives the same error

**Comment by bhanuka96** [comment]
> > > If I even try this implementation from the API docs: https://pub.dev/documentation/cloud_functions/latest/cloud_functions/HttpsCallable/call.html the error still occurs
> > 
> > 
> > for me it's working.. I deleted +7 project and other new cloud function project and then install`cloud_functions: 0.4.1+7`
> 
> Does not work. +7 still gives the same error

sorry not +7 , +6, i edited my answer

**Comment by mark-veenstra** [comment]
> sorry not +7 , +6, i edited my answer

Lol... Downgrading is **NOT AN OPTION** as mentioned several times downgrading introduces back the `DEADLINE_EXCEEDED`.

I understand how to downgrade, so please do not keep referring to downgrading! I would like to use the `+7` version because it **FIXES** the `DEADLINE_EXCEEDED` error...

**Comment by mark-veenstra** [comment]
@Jbz797 I found a solution for Android. The following line: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java#L28

You see the `MethodChannel` is `cloud_functions`, but the channel invoked is on channel `plugins.flutter.io/cloud_functions`, so change it to `plugins.flutter.io/cloud_functions` and it works on Android...

So to do it quick and dirty. Install the latest version (`+7`) and then in the external libraries find the file and change it. Run your build and you are good to go.

**Comment by Jbz797** [comment]
Good job ;)
I think its `cloud_functions` to replace with `plugins.flutter.io/cloud_functions`.

**Comment by collinjackson** [comment]
Thanks everyone for looking into this. This should have been caught by our CI but wasn't due to a bug. I filed https://github.com/FirebaseExtended/flutterfire/issues/1870 for that.

**Comment by collinjackson** [comment]
Opened a PR here fixing the CI issue: https://github.com/FirebaseExtended/flutterfire/pull/1871

**Comment by collinjackson** [comment]
Fixed in #1868, please update to 0.4.1+8

**Comment by AlexandreRoba** [comment]
This not solved. I’m running version 0.4.2. and I’m getting the same error message on IOS. The pod is available and install in the iOS solution.

**Comment by leminhph** [comment]
Looks like a recent merge (https://github.com/FirebaseExtended/flutterfire/pull/1707) undid the fix in https://github.com/FirebaseExtended/flutterfire/pull/1868

**Comment by mark-veenstra** [comment]
They broke it for iOS and MacOS since they added the MacOS support.

This line: https://github.com/FirebaseExtended/flutterfire/pull/1707/files#diff-be4909e1a5fea71b5512f72d04fa70f5R18

Should change the `methodChannelWithName`, like this: https://github.com/FirebaseExtended/flutterfire/pull/1868/files#diff-92452171f84c200dcc4497f4b57baec3R18

**Comment by leminhph** [comment]
Can someone please reopen this ticket to track its actual status?

**Comment by jpv123** [comment]
Same problem here on iOS. Any news?

**Comment by leminhph** [comment]
Looks like it's fixed in `0.4.2+2`.

Relevant MR: https://github.com/FirebaseExtended/flutterfire/pull/2051

**Comment by amjadyahya1** [comment]
Same here, version ^0.4.2+3 gives the same error. God, is it so hard to fix.

**Comment by AndresArdilaB** [comment]
> Looks like it's fixed in `0.4.2+2`.
> 
> Relevant MR: #2051

This works for me, thanks man!

**Comment by shoxter** [comment]
I'm getting this on 0.5.0? Do I need to do something to fix this?
