### ISSUE TITLE
[Firestore] Firestore not receiving updates on physical device.

### ISSUE THREAD

**Issue by DavidRG13** [FirebaseExtended/flutterfire#2861]
**Description**
We are using Firestore real-time updates and that's working as expected everywhere except a Huawei Mate 9.
We've tried over WiFi and LTE, no luck. Working in another Mate 9.
Not seeing anything in logcat.

Is there anything else we could check to provide more info?

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-ES)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2 EAP)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @DavidRG13 
Same Mate 9 device, issue on one and no one another? 
This could be device issue and not an issue with firestore itself

**Comment by Chimba123** [comment]
@DavidRG13 for me I am using an iPhone X when I update to v1.17.4 I have noticed firestore data is not being queried amd displayed onto my device but previously it was working

**Comment by Chimba123** [comment]
@TahaTesser 
`Column(
        children: <Widget>[
          StreamBuilder<QuerySnapshot>(
              stream: Firestore.instance.collection('Messages').snapshots(),
              builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
                if (snapshot.hasError)
                  return Center(child: new Text('Error: ${snapshot.error}', style: TextStyle(color:Colors.red),));
                switch (snapshot.connectionState) {
                  case ConnectionState.waiting:
                    return Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          CupertinoActivityIndicator(radius: 8.5,),
                          Text('Loading messages...', style: TextStyle(color: Colors.grey[600]),),
                        ],
                      ),
                    );
                  default:
                    return Flexible(
                        child: new ListView.builder(
                          padding: new EdgeInsets.all(8.0),
                          reverse: true,
                          itemBuilder: (context, int index) => _buildMessageItem(snapshot.data.documents[index]),
                          itemCount: snapshot.data.documents.length,
                        ));
                }

              }),

          Expanded(
              child:   Align(
                alignment: Alignment.bottomCenter,
                child: new Container(
                  decoration: new BoxDecoration(color: Theme.of(context).cardColor),
                  child: _buildTextComposer(),
                ),
              ),
          ),
        ],
      )`

here is my code nothing is deing displayed

**Comment by DavidRG13** [comment]
Thanks @Chimba123, could you tell us which flutter and cloud_firestore versions were the ones working for you?

**Comment by Chimba123** [comment]
Flutter v1.17.3

**Comment by TahaTesser** [comment]
@DavidRG13  @Chimba123 
Please try this code sample, tried physical iPhone XR

<img width="1039" alt="Screenshot 2020-07-02 at 2 38 18 PM" src="https://user-images.githubusercontent.com/48603081/86339870-b90a2e80-bc71-11ea-89e2-e5f638ee5563.png">


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: BookList(),
      ),
    );
  }
}

class BookList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        StreamBuilder(
            stream: Firestore.instance.collection('Messages').snapshots(),
            builder:
                (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
              if (snapshot.hasError)
                return Center(
                    child: new Text(
                  'Error: ${snapshot.error}',
                  style: TextStyle(color: Colors.red),
                ));
              switch (snapshot.connectionState) {
                case ConnectionState.waiting:
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Text(
                          'Loading messages...',
                          style: TextStyle(color: Colors.grey[600]),
                        ),
                      ],
                    ),
                  );
                default:
                  return new ListView.builder(
                      shrinkWrap: true,
                      padding: new EdgeInsets.all(8.0),
                      reverse: true,
                      itemCount: snapshot.data.documents.length,
                      itemBuilder: (context, int index) {
                        return ListTile(
                            title: Text(snapshot.data.documents[index].data
                                .toString()));
                      });
              }
            }),
        // Expanded(
        //   child: Align(
        //     alignment: Alignment.bottomCenter,
        //     child: new Container(
        //       decoration: new BoxDecoration(color: Theme.of(context).cardColor),
        //       child: _buildTextComposer(),
        //     ),
        //   ),
        // ),
      ],
    );
  }
}

``` 

</details> 

![flutter_01](https://user-images.githubusercontent.com/48603081/86339964-db9c4780-bc71-11ea-9994-97877d66ea82.png)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (9 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by Chimba123** [comment]
@TahaTesser tried it but it’s stuck on the “loading messages...” and not retrieving the actual data from Firebase 😔... what could I be doing wrong?

**Comment by Chimba123** [comment]
I have found the problem it was my rules it locked up after the trial period its working fine now. I thought I had relaxed the rules

**Comment by Ehesp** [comment]
Currently error from stream based listeners aren't being handled, so it'll just "hang" in a state of waiting for data forever. This has been fixed and will land with #2582 update.

**Comment by DavidRG13** [comment]
Hi,

We've been doing some tests, but it still doesn't connect from an iPhone nor my specific Huawei Mate 9. Downgraded to flutter 1.17.3, no changes.
Are there any differences between a debug and a release flutter build that could affect this? Everything works when connecting any device to the laptop, but failing to connect when we release a beta version to Testflight/AppDistribution.

Running with `--verbose` doesn't give any useful/related information.

We have our Firestore security rules as test mode, so it should not be related to that.

Is the setup instructions up to date? https://pub.dev/packages/cloud_firestore

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, stream errors are now bubbled through so the underlying errors should now show through - this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
