### ISSUE TITLE
🐛 [Firebase Messaging] Firebase.onMessage stream does not activate till the FcmToken is fetched on Android

### ISSUE THREAD

**Issue by chillbrodev** [FirebaseExtended/flutterfire#4046]
## Bug report

Hey all, thanks for all the hard work on getting this plugin suite ready. This question is focused on Android and the `FirebaseMessaging.onMessage.listen(...)` stream. 

I am using these versions
firebase_core: "^0.5.1"
firebase_messaging: "^8.0.0-dev.5"

It seems like this onMessage stream never activates until some action happens like requesting the FCM Token. When I launch my app and run the Firebase.initializeApp(), I get successful initialization, and I register the `onMessage` in the same init function. When I send a message, my listen function doesn't fire until I request the FCM token. However, if I never call `FirebaseMessaging.instance.getToken();` the `FirebaseMessaging.onMessage.listen(...) stream` never activates and the `.listen()` never fires.

Here are my functions: initialize(), setPushListener() and fetchFcmToken()

```
Future<void> initialize() async {
    if (_firebaseApp == null) {
      try {
        _firebaseApp = await Firebase.initializeApp();
        await setPushListener();
        await fetchFcmToken();

        emit(HomeReadyState(true));
      } catch (err) {
        emit(HomeReadyState(false));
      }
    }
  }


  Future<void> setPushListener() async {
    print('Set Push Listener');
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('Got a message whilst in the foreground!');
      print('Message data: ${message.data}');

      if (message.notification != null) {
        print('Message also contained a notification: ${message.notification}');
      }
    });
  }

  Future<void> fetchFcmToken() async {
    if (_firebaseApp == null) {
    } else {
      final token = await FirebaseMessaging.instance.getToken();
      print('FCM Token is:' + token);
    }
  }
```

### Steps to reproduce

1. Integrate Flutter Fire into Flutter Application.
2. Initialize Firebase App.
3. Setup FirebaseMessaging.onMessage.listen(...) in initState method.
4. Do NOT call FirebaseMessaging.instance.getToken()
5. With the app in foreground, Send a push notification.
6. Watch logs for no `onMessage` logs.

### Expected behavior

---
It is expected that the FirebaseMessaging.onMessage.listen(...) executes and runs the code inside .listen().

OR 

If it is expected that FirebaseMessaging.instance.getToken() should be called then please indicate this with an exception or appropriate log message.

## Additional context

None

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.2
Flutter SDK 1.22.2
flutter_app_twilio 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- equatable 1.2.5 [collection meta]
- firebase_core 0.5.1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 8.0.0-dev.5 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.0.6 [flutter bloc provider]
- twilio_voice_plugin 0.0.1 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- bloc 6.1.0 [meta]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.2 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.3 [flutter meta firebase_core plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- pedantic 1.9.2 [meta]
- plugin_platform_interface 1.0.3 [meta]
- provider 4.3.2+2 [flutter nested collection]
- quiver 2.1.4+1 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by Salakar** [comment]
Please can you try `8.0.0-dev.6` - some other issues have been fixed which may have been causing this issue.

**Comment by chillbrodev** [comment]
@Salakar It looks to be partially resolved.

I set the listener without calling the getToken and in my logs I only saw `D/FLTFireMsgReceiver: broadcast received for message` when my push was sent with the app in the foreground. 

When the app is in the background, the background message handler fires correctly and displays my logs. 

It seems to be an issue when the app is in the foreground.

My current workaround of registering the FCM token will suffice as it is best practice to always re-register the device token when the app launches. I'll keep an eye on the releases and post back here with any updates.
