### ISSUE TITLE
🐛 [firebase_auth] [0.20.0+1] verifyPhoneNumber function never executes even after getting sms.

### ISSUE THREAD

**Issue by Shiba-Kar** [FirebaseExtended/flutterfire#4724]
## Bug report

**Describe the bug**
[firebase_auth] [0.20.0+1] verifyPhoneNumber function never executes even after getting sms. Then after codeAutoRetrievalTimeout is called.

### Steps to reproduce

```

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'dart:developer';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void onButtonPressed() async {
    FirebaseAuth _auth = FirebaseAuth.instance;
    await _auth
        .verifyPhoneNumber(
      phoneNumber: '+91xxxxxxxxxx',
      verificationCompleted: (PhoneAuthCredential credential) async {
        var x = await _auth.signInWithCredential(credential);
        var y = await x.user.getIdToken();
        log('Token==== $y');
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        log('codeAutoRetrievalTimeout');
      },
      codeSent: (String verificationId, int forceResendingToken) {
        log('codeSent');
      },
      verificationFailed: (FirebaseAuthException error) {
        print("Someting went wrong !! $error");
      },
    )
        .catchError((onError) {
      print(onError);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Container(),
      floatingActionButton: FloatingActionButton(onPressed: onButtonPressed),
    );
  }
}

```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[  +99 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78910062997c3a836feee883712c241a5fd22983
[        ] executing: [C:\flutter/] git tag --points-at HEAD
[  +42 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +16 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] Skipping request to fetchTags - on well known channel stable.
[        ] executing: [C:\flutter/] git tag --points-at HEAD
[  +37 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.5
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +71 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +14 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +80 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 6 weeks ago
[  +49 ms] java -version
[  +14 ms] executing: C:\Users\shiva\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +15 ms] [√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
[   +1 ms]     • Flutter version 1.22.5 at C:\flutter
[        ]     • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
[        ]     • Engine revision ae90085a84
[  +48 ms]     • Dart version 2.10.4
\[  +66 ms] List of devices attached
           4ec459c7               device product:whyred model:Redmi_Note_5_Pro device:whyred transport_id:4
[  +10 ms] C:\Users\shiva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4ec459c7 shell getprop
|[  +61 ms] executing: C:\Users\shiva\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
[  +64 ms] ro.hardware = qcom
[   +6 ms] executing: C:\Users\shiva\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
/[  +25 ms] List of devices attached
           4ec459c7               device product:whyred model:Redmi_Note_5_Pro device:whyred transport_id:4
[+1197 ms] [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[   +1 ms]     • Android SDK at C:\Users\shiva\AppData\Local\Android\sdk
[   +1 ms]     • Platform android-30, build-tools 30.0.3
[   +1 ms]     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[        ]     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[   +1 ms] [!] Android Studio (version 4.1.0)
[  +31 ms]     • Android Studio at C:\Program Files\Android\Android Studio
[   +2 ms]     X Flutter plugin not installed; this adds Flutter specific functionality.
[   +1 ms]     X Dart plugin not installed; this adds Dart specific functionality.
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[   +2 ms] [√] VS Code, 64-bit edition (version 1.52.1)
[   +1 ms]     • VS Code at C:\Program Files\Microsoft VS Code
[        ]     • Flutter extension version 3.18.1
[   +1 ms] [√] Connected device (1 available)
[   +1 ms]     • Redmi Note 5 Pro (mobile) • 4ec459c7 • android-arm64 • Android 9 (API 28)
[        ] ! Doctor found issues in 2 categories.
[   +9 ms] "flutter doctor" took 2,045ms.
[ +279 ms] ensureAnalyticsSent: 267ms
[   +4 ms] Running shutdown hooks
[  +10 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5
firebase_phone_auth 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]  
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- pedantic 1.9.2 [meta]
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by Shiba-Kar** [comment]
Have you tried running the official example?
*In example also verifyPhoneNumber function is not called.* 

 Is the codeSent callback being called?
 *Yes*

Are any errors thrown?
*```  implementation "androidx.browser:browser:1.2.0" ``` added to stop the app crash.*

**Comment by markusaksli-nc** [comment]
Have you done this https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification?

Are you getting ReCaptcha when sending the code?

**Comment by Shiba-Kar** [comment]
> Have you done this https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification?
> 
> Are you getting ReCaptcha when sending the code?

yess

**Comment by Shiba-Kar** [comment]
Have you done this https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification?
Yess getting is error
```
E/FirebaseAuth(13649): [SmsRetrieverHelper] SMS verification code request failed: unknown status code:17028 A safety_net_token was passed, but no matching SHA-256 was registered in the Firebase console. Please make sure that this application’s packageName/SHA256 pair is registered in the Firebase Console.
```
> Are you getting ReCaptcha when sending the code?
yess

**Comment by markusaksli-nc** [comment]
You are getting this error because you have not added your SHA 256 to Firebase Console.

You need to run `cd android` and `gradlew signingReport` to get the key.

**Comment by Shiba-Kar** [comment]
> You likely only have your SHA 1 key in Firebase Console since you just did this. You are getting this error because you have not added your SHA 256 to Firebase Console.
> 
> You need to run `cd android` and `gradlew signingReport` to get the key and then add it in project settings as well.

Done now it works.

**Comment by markusaksli-nc** [comment]
Does the `verificationCompleted` callback still not get called?

**Comment by Shiba-Kar** [comment]
> Does the `verificationCompleted` callback still not get called?

Now all works as it should !! Thanks

**Comment by markusaksli-nc** [comment]
Closing this as solved then, glad I could help.

**Comment by priezz** [comment]
Hello, I have exactly the same issue with `firebase_auth` version 0.20.0+1, all SHA1 and SHA-256 are added into the Firebase console. The problem does no exist with the prior versions (0.18.3 and below).

**Comment by cedvdb** [comment]
> Have you done this https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification?


This isn't in the doc btw

**Comment by madatr** [comment]
> > Does the `verificationCompleted` callback still not get called?
> 
> Now all works as it should !! Thanks

Hi, how did you get it to work?

Thanks,
