### ISSUE TITLE
🐛 [cloud_firestore] FirebaseException/PlatformException.

### ISSUE THREAD

**Issue by larssn** [FirebaseExtended/flutterfire#5064]
### Version 0.16.0

**Describe the bug**
Until recently, errors like "unavailable" (which happens on a spotty internet connection, and using runTransaction) would throw a `FirebaseException`. Now a `PlatformException` is thrown instead.

Is this a regression or intentional?

Stacktrace:
```
PlatformException: PlatformException(firebase_firestore, UNAVAILABLE: End of stream or IOException, {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.}, null)
  File "message_codecs.dart", line 582, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 159, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "platform_channel.dart", line 359, in MethodChannel.invokeMapMethod
  File "<asynchronous suspension>"
  File "method_channel_transaction.dart", line 45, in MethodChannelTransaction.get
  File "<asynchronous suspension>"
  File "transaction.dart", line 26, in Transaction.get
  File "<asynchronous suspension>"
  File "preparation_block_repo.dart", line 66, in PreparationBlockRepository.claim.<fn>
  File "<asynchronous suspension>"
  File "firestore.dart", line 167, in FirebaseFirestore.runTransaction.<fn>
  File "<asynchronous suspension>"
  File "method_channel_firestore.dart", line 210, in MethodChannelFirebaseFirestore.runTransaction.<fn>
```

### Steps to reproduce

1. Turn off internet on device
2. Use `runTransaction`

Alternatively, there seems to be a test for this exact scenario.

### Expected behavior

I expect a standard for exceptions thrown by the plugin.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.13.6 17G14042 darwin-x64, locale en-DK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doesn't work anymore:
The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".
```

</details>

---

**Comment by larssn** [comment]
My catch handlers now have to look like this:

```
    try {
      await FirebaseFirestore.instance.runTransaction(myHandler);
    } on FirebaseException catch (err) {
      if (err.code == 'unavailable') {
        // handle offline
      } else {
        rethrow;
      }
    } on PlatformException catch (err) {
      if (err.details['code'] == 'unavailable') {
        // handle offline
      } else {
        rethrow;
      }
    }
```

**Comment by larssn** [comment]
@markusaksli-nc Sorry, but this is not a question, is a regression.

**Comment by larssn** [comment]
@markusaksli-nc Seems to have been caused by this PR: https://github.com/FirebaseExtended/flutterfire/pull/4209 and specifically this commit: https://github.com/FirebaseExtended/flutterfire/commit/b4386b33c6f573fbee80a877cf8a630861f424ae

A lot of code that used to convert `PlatformExceptions` into `FirebaseFirestoreExceptions` have been removed.

**Comment by larssn** [comment]
@ened Thoughts?

**Comment by ened** [comment]
@larssn oh no, sorry if #4209 caused issues for you.
You said there is an existing test which covers this - so it should be easy enough to devise a fix. 
I'll try to make time this week to look at solutions.

In general, this probably _should_ be a FirebaseException. @rrousselGit @Salakar do you agree?

**Comment by larssn** [comment]
@ened No worries, these things happen. 🙂
We caught it pretty quickly.

> In general, this probably should be a FirebaseException
Well it used to. It was introduced in 0.14: _"Any Firestore specific errors now return a FirebaseException"_

I'm in favour of it still doing that.

**Comment by larssn** [comment]
@ened Did you ever get around to try and fixing this?

**Comment by ened** [comment]
@larssn no, but looks like @rrousselGit is working on it [right now](https://github.com/FirebaseExtended/flutterfire/pull/5783#issuecomment-820553652).

**Comment by Salakar** [comment]
Thanks for the report on this, this should have been solved now by #5783 as mentioned above. This will be released in the next couple of days.

**Comment by rrousselGit** [comment]
No, #5783 is separate
I'll deal with this issue but it isn't fixed yet

**Comment by russellwheatley** [comment]
It appears so. All the tests we run for Firestore CI are checking for `FirebaseException` as can be seen [here](https://github.com/FirebaseExtended/flutterfire/blob/e3012742067fba86fade8c837b462cb584b60d26/packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart#L295), [here](https://github.com/FirebaseExtended/flutterfire/blob/51166de60d007e4f28006dab6e83259ab4a5eb23/packages/cloud_firestore/cloud_firestore/example/test_driver/transaction_e2e.dart#L161) & [here](https://github.com/FirebaseExtended/flutterfire/blob/1f8d79a3ee2ab6e5a73cd57d1ce164bccfe14879/packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart#L159).
