### ISSUE TITLE
🐛 [Firebase_Auth] Phone Auth keep crash on IOS

### ISSUE THREAD

**Issue by Peng-Qian** [FirebaseExtended/flutterfire#5464]
## Bug report

`PhoneAuthProvider.credential` or `signInWithCredential`will result in a crash with any parameter on IOS after update firebase_core to 1.0.2

### Steps to reproduce

1.  Call this API on an IOS emulator or real device

### Expected behavior

NO Crash

### Additional Infomation

1. I have successfully implement SMS auth for a long time and haven't change anything
2. This bug will just crash the app without any Exception. I manually tracked this and it seems App crash after calling `PhoneAuthProvider.credential` and `signInWithCredential`.

#### Sample Code
```dart
      print('verificationId on input sms code: $verificationId');
      print('smsCode: $smsCode');
      print('before call PhoneAuthProvider.credential');
      final authCredential = PhoneAuthProvider.credential(
        verificationId: verificationId,
        smsCode: smsCode,
      );
      print('after call PhoneAuthProvider.credential');
      print('authCredential.providerId: ${authCredential.providerId}');
      print('authCredential.token: ${authCredential.token}');
      print('authCredential.signInMethod: ${authCredential.signInMethod}');
      print('before call signInWithCredential');
      final result = await _firebaseAuth.signInWithCredential(authCredential);
      print('after call signInWithCredential');
      print('result.user.uid: ${result.user.uid}');
```

#### Output
```dart
flutter: verificationId on codeSent: ... // same to below
flutter: verificationId on input sms code: ... // same to above (some time print end here, maybe just fail to print following info when crash)
flutter: smsCode: 121212
flutter: before call PhoneAuthProvider.credential
flutter: after call PhoneAuthProvider.credential
flutter: authCredential.providerId: phone
flutter: authCredential.token: null // always null no matter sms code is right or not
flutter: authCredential.signInMethod: phone
flutter: before call signInWithCredential // crash here
```

#### Possible problem
- Android phone work perfectly
- I also use signInWithCredential on the third part login and it works perfectly. 
- I guess something wrong with the `PhoneAuthProvider.credential` or phone sign-in method of `signInWithCredential` on the IOS part

**Comment by markusaksli-nc** [comment]
Hi @Peng-Qian 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you provide the output of `flutter doctor -v` when it crashes?
Thank you

**Comment by Peng-Qian** [comment]
```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-NZ)
    • Flutter version 2.1.0-12.2.pre at /Users/pq/Developer/SDK/flutter
    • Framework revision 5bedb7b1d5 (3 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/pq/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • E32A9A4C-EA7C-4C6F-AC08-B35179C19C60 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!
```

```
Dart SDK 2.13.0-116.0.dev
Flutter SDK 2.1.0-12.2.pre
echo 1.0.0+1

dependencies:
- animations 2.0.0 [flutter]
- bloc 6.1.3 [meta]
- blurhash_dart 1.0.0 [image]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- cached_network_image 3.0.0-nullsafety [flutter flutter_cache_manager octo_image]
- cloud_firestore 1.0.4 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.2
- dartz 0.9.2
- equatable 2.0.0 [collection meta]
- file 6.1.0 [meta path]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 6.1.2 [firebase_core flutter]
- firebase_dynamic_links 0.8.0 [flutter firebase_core]
- firebase_storage 8.0.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flare_flutter 3.0.0 [collection flutter meta]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.3 [flutter bloc provider]
- flutter_blurhash 0.5.4-nullsafety.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_hooks 0.16.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_slidable 0.5.7 [flutter]
- flutter_spinkit 5.0.0 [flutter]
- flutter_sticky_header 0.5.0 [flutter value_layout_builder]
- font_awesome_flutter 9.0.0 [flutter]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- geocoding 2.0.0 [flutter geocoding_platform_interface]
- geolocator 7.0.1 [flutter geolocator_platform_interface geolocator_web]
- get_it 5.0.6 [async meta]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- google_maps_flutter 2.0.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_webservice 0.0.20-nullsafety.3 [http meta json_annotation]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- http 0.13.1 [http_parser meta path pedantic]
- image 3.0.2 [archive meta xml]
- image_cropper 1.4.0 [flutter]
- image_gallery_saver 1.6.8 [flutter]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- injectable 1.1.2 [get_it]
- intl 0.17.0 [clock path]
- material_floating_search_bar 0.3.3 [flutter meta]
- modal_bottom_sheet 2.0.0 [flutter]
- octo_image 1.0.0-nullsafety.1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pedantic 1.11.0
- permission_handler 6.1.1 [flutter meta permission_handler_platform_interface]
- photo_manager 1.0.6 [flutter]
- photo_view 0.11.1 [flutter]
- pin_code_fields 7.0.0 [flutter]
- provider 4.3.3 [collection flutter nested]
- recase 3.0.1
- rxdart 0.26.0
- share 2.0.1 [meta mime flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- sign_in_with_apple 3.0.0 [flutter meta]
- sliding_up_panel 1.0.2 [flutter]
- sliver_tools 0.2.1 [flutter]
- transparent_image 2.0.0
- uuid 3.0.3 [crypto]
- wakelock 0.5.0+2 [flutter meta wakelock_macos wakelock_windows wakelock_platform_interface wakelock_web]

dev dependencies:
- bloc_test 7.1.0 [bloc test meta mockito]
- build_runner 1.11.5 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- built_value_generator 8.0.4 [analyzer build build_config built_collection built_value source_gen quiver]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.12.7 [analyzer build build_config meta source_gen freezed_annotation]
- injectable_generator 1.1.2 [build source_gen path glob analyzer meta code_builder dart_style injectable collection]

dependency overrides:
- analyzer 1.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 2.0.0
- crypto 3.0.1 [collection typed_data]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- json_annotation 4.0.1
- plugin_platform_interface 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- yaml 3.1.0 [collection source_span string_scanner]

transitive dependencies:
- _fe_analyzer_shared 19.0.0 [meta]
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.3 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.6 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.4 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.10 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.4 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- coverage 1.0.2 [args logging package_config path source_maps stack_trace vm_service]
- dart_style 1.3.14 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geocoding_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 2.0.0 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.2 [flutter flutter_web_plugins geolocator_platform_interface]
- google_maps_flutter_platform_interface 2.0.2 [flutter meta plugin_platform_interface stream_transform collection]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- mockito 4.1.4 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- nested 1.0.0 [flutter]
- node_preamble 1.4.13
- package_config 2.0.0 [path]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- permission_handler_platform_interface 3.1.1 [flutter meta plugin_platform_interface]
- petitparser 4.0.2 [meta]
- platform 3.0.0
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.0.0 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- value_layout_builder 0.2.0 [flutter]
- vector_math 2.1.0
- vm_service 6.1.0+1
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]

```

**Comment by darshankawar** [comment]
@Peng-Qian 
Can you try the official `firebase_auth` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and check if you get same error / crash ?

**Comment by Salakar** [comment]
I think this is potentially fixed by #5675

**Comment by Peng-Qian** [comment]
not really fixed, this bug still there in non-null-safety dart SDK version
