### ISSUE TITLE
[cloud_firestore] Compatibility issues Api 21-

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#698]
Cloud Firestore has some Compatibility issues with other plugins from firebase&google
when i add cloud firestore alone ,, it builds and run perfectly
when i just add other plugins ex: auth , gSignIn
app doesn't start on kitkat for example
but starts on lolipop+

Steps to re produce error:
1- New project package name (com.debug.flutterbugs)
2- added in pubspec.yaml
```
  cloud_firestore: ^0.7.4
  firebase_auth: ^0.5.18
  google_sign_in: ^3.0.4
```
3- enabled multidex by adding in App gradle
```
multiDexEnabled true
```

4- applied firebase instructions [here](https://firebase.google.com/docs/android/setup#add_the_sdk)
5- Just added imports to the `main.dart`

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
```
Run app on kitkat and lolipop devices
Log Cats :

```
08-19 21:11:56.485 W/ActivityManager(335): Invalid packageName: com.debug.flutterbugs
08-19 21:12:19.885 I/Finsky  (3129): [1] com.google.android.finsky.verifier.impl.ez.c(173): Verification complete: id=1, package_name=com.debug.flutterbugs
08-19 21:12:22.385 I/PackageManager(335): Running dexopt on: com.debug.flutterbugs
08-19 21:12:22.585 I/ActivityManager(335): Force stopping com.debug.flutterbugs appid=10036 user=-1: update pkg
08-19 21:12:22.755 D/BackupManagerService(335): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.debug.flutterbugs flg=0x4000010 (has extras) }
08-19 21:12:22.875 I/Finsky  (3129): [1] com.google.android.finsky.externalreferrer.b.a(6): Package state data is missing for com.debug.flutterbugs
08-19 21:12:24.405 I/ActivityManager(335): START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.debug.flutterbugs/.MainActivity (has extras)} from pid 3213
08-19 21:12:24.455 I/ActivityManager(335): Start proc com.debug.flutterbugs for activity com.debug.flutterbugs/.MainActivity: pid=3224 uid=10036 gids={50036, 3003}
08-19 21:12:24.495 E/AndroidRuntime(3224): Process: com.debug.flutterbugs, PID: 3224
08-19 21:12:24.495 E/AndroidRuntime(3224): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.debug.flutterbugs-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.debug.flutterbugs-1, /system/lib]]
08-19 21:12:24.495 E/AndroidRuntime(3224): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.debug.flutterbugs-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.debug.flutterbugs-1, /system/lib]]
08-19 21:12:24.495 W/ActivityManager(335):   Force finishing activity com.debug.flutterbugs/.MainActivity
08-19 21:12:25.275 W/ActivityManager(335): Activity pause timeout for ActivityRecord{4aa51ce0 u0 com.debug.flutterbugs/.MainActivity t11 f}
08-19 21:12:34.445 E/WindowManager(335): Starting window AppWindowToken{4ab51de8 token=Token{4aa2ee30 ActivityRecord{4aa51ce0 u0 com.debug.flutterbugs/.MainActivity t11}}} timed out
08-19 21:12:35.715 W/ActivityManager(335): Activity destroy timeout for ActivityRecord{4aa51ce0 u0 com.debug.flutterbugs/.MainActivity t11 f}
08-19 21:15:03.795 I/ActivityManager(335): Process com.debug.flutterbugs (pid 3224) has died.
```

Lolipop:

```
08-19 21:36:17.915 D/PackageManager(1640): Renaming /data/app/vmdl1843307703.tmp to /data/app/com.debug.flutterbugs-1
08-19 21:36:17.960 I/PackageManager(1640): Running dexopt on: /data/app/com.debug.flutterbugs-1/base.apk pkg=com.debug.flutterbugs isa=x86 vmSafeMode=false
08-19 21:36:18.312 I/dex2oat (4544): /system/bin/dex2oat --zip-fd=5 --zip-location=/data/app/com.debug.flutterbugs-1/base.apk --oat-fd=6 --oat-location=/data/dalvik-cache/x86/data@app@com.debug.flutterbugs-1@base.apk@classes.dex --instruction-set=x86 --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=7
08-19 21:36:27.414 V/BackupManagerService(1640): restoreAtInstall pkg=com.debug.flutterbugs token=3 restoreSet=0
08-19 21:36:27.590 D/BackupManagerService(1640): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.debug.flutterbugs flg=0x4000010 (has extras) }
08-19 21:36:27.591 W/BackupManagerService(1640): Removing schedule queue dupe of com.debug.flutterbugs
08-19 21:36:43.088 I/ActivityManager(1640): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.debug.flutterbugs/.MainActivity bnds=[431,618][572,848]} from uid 1000 on display 0
08-19 21:36:43.093 V/WindowManager(1640): addAppToken: AppWindowToken{32477e92 token=Token{275e9c1d ActivityRecord{250edcf4 u0 com.debug.flutterbugs/.MainActivity t19}}} to stack=1 task=19 at 0
08-19 21:36:43.095 V/WindowManager(1640): Adding window Window{1124d68c u0 Starting com.debug.flutterbugs} at 4 of 7 (after Window{277b641c u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
08-19 21:36:43.149 I/ActivityManager(1640): Start proc 4618:com.debug.flutterbugs/u0a37 for activity com.debug.flutterbugs/.MainActivity
08-19 21:36:43.300 I/FA      (4618):   adb shell setprop debug.firebase.analytics.app com.debug.flutterbugs
08-19 21:36:44.767 V/WindowManager(1640): Adding window Window{3fa8b042 u0 com.debug.flutterbugs/com.debug.flutterbugs.MainActivity} at 4 of 8 (before Window{1124d68c u0 Starting com.debug.flutterbugs})
08-19 21:36:44.879 V/WindowManager(1640): Adding window Window{37d81590 u0 SurfaceView} at 4 of 9 (before Window{3fa8b042 u0 com.debug.flutterbugs/com.debug.flutterbugs.MainActivity})
08-19 21:36:45.554 I/ActivityManager(1640): Displayed com.debug.flutterbugs/.MainActivity: +2s429ms
08-19 21:36:52.158 W/PackageManager(1749): Failure retrieving resources for com.debug.flutterbugs: Resource ID #0x00
```

flutter upgrade & doctor : 

```
flutter upgrade
Upgrading Flutter from C:\flutterSDK...
Already up to date.
Upgrading engine...
Already up-to-date.
Flutter 0.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision e4b989bf3d (10 days ago) • 2018-08-09 09:45:44 -0700
Engine • revision 3777931801
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c
Running "flutter packages upgrade" in flutter_bugs...       15.9s
```

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.8, on Microsoft Windows [Version 10.0.17134.191], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] Connected devices (1 available)
• No issues found!
```

the same issue on beta channel , so it doesn't matter if I am on dev

**Comment by kroikie** [comment]
@Saifallak

The issue at https://github.com/flutter/flutter/issues/20801 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @Saifallak
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by MP00** [comment]
Hi **@iapicca**
I have this issue.
To reproduce it:

-Add package cloud_firestore: (latest version - 0.12.10+2) in pubspec.yaml
-run default app in device with api smaller of 21

[flutter run --verbose.txt](https://github.com/FirebaseExtended/flutterfire/files/3866981/flutter.run.--verbose.txt)
[flutter_doctor.txt](https://github.com/FirebaseExtended/flutterfire/files/3866982/flutter_doctor.txt)
[logcat.txt](https://github.com/FirebaseExtended/flutterfire/files/3866983/logcat.txt)
[flutter build --verbose.txt](https://github.com/FirebaseExtended/flutterfire/files/3866984/flutter.build.--verbose.txt)

**Comment by MP00** [comment]
The androidx.core: core package contained a bug related to compatibility with olds api's (compat), fixed in version 1.10-beta01: https://developer.android.com/jetpack/androidx/releases/core#1.1.0-beta01  (*Fixed exception when loading font on devices running API Level 20 and lower)

Apparently the FirebaseApp.class is using androidx.core 1.00 package in the dependencies, what would cause the bug reported in this issue.

![image](https://user-images.githubusercontent.com/24235471/69750249-13b33900-112b-11ea-9ed7-00156bde38ce.png)

**Comment by iapicca** [comment]
Hi @MP00 and @Saifallak
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of cloud_firestore?
thank you

**Comment by Saifallak** [comment]
Yea problem still there, with dev channel and latest plugin version

**Comment by MP00** [comment]
Hi @iapicca,

This issue not fixed. 
cloud_firestore v0.13.0+1 
Flutter  v1.12.13+hotfix.7

**Comment by Unknownymous** [comment]
> Hi @MP00 and @Saifallak
> are you still experiencing the issue with the latest stable version of flutter
> and the latest version of cloud_firestore?
> thank you

Hi @iapicca 

Yes, still not fix with latest version of flutter and dart.
my app crashed and won't open.

![flutter version](https://user-images.githubusercontent.com/6735081/81254555-0a28e800-905e-11ea-97d3-2480b3bc1ef4.jpg)

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
