### ISSUE TITLE
🐛 [cloud_functions] FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#7446]
## Bug report

**Describe the bug**

On my real Android device i have the following warning after running a ```flutter clean``` and rebuild :

```
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.1.1/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

### Steps to reproduce

1. Run ```flutter clean```
2. Build any app with ```cloud_functions: ^3.1.1``` on a real Android device 
3. See the warning

### Expected behavior

FlutterFirebaseFunctionsPlugin.java should not uses or overrides a deprecated API.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • CPH1931 (mobile) • ee9b32b5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. There have been similar warnings reported on other flutterfire plugins as well, https://github.com/FirebaseExtended/flutterfire/issues/3876
I do see the same behavior and warning message upon using latest plugin version.

```
flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.1.1/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
These are probably coming from plugin itself using deprecated apis, although they are just warnings and won't harm or cause any unusual behavior in the app.

**Comment by Tom3652** [comment]
The issue you mentioned is about much older versions of the plugin, it seems to be fixed for all packages (auth, analytics, core) in the latest versions :)

**Comment by Salakar** [comment]
Yep, this was fixed a while back so I'm going to close this issue. Thanks for the report!

**Comment by Tom3652** [comment]
Unfortunately i am still having these warnings : 

```
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.1/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.0/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.0/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.0/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

I have upgraded this morning to the latests versions of the plugins and would also like to thank you for your work by the way :)

**Comment by darshankawar** [comment]
@Tom3652 
Can you try the latest plugin version ^3.2.3 ?

**Comment by Tom3652** [comment]
```
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.3/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.2/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.2/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.2/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

Could this be linked to my ```build.gradle``` files configuration ? 
Here is the ```app/build.gradle``` :

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myappname.android"
        minSdkVersion 24
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
}
```

And my ```build.gradle``` file at project directory : 

```
buildscript {
    ext.kotlin_version = '1.6.0'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext.flutterFFmpegPackage  = "min-gpl-lts"
```

**Comment by darshankawar** [comment]
I verified this using latest plugin version and on latest stable and do see the warning.
Reopening.

**Comment by Salakar** [comment]
I'm looking at adding a CI stage for this to pick these up before a release - so will get these fixed as part of this

**Comment by gOzaru** [comment]
Does this bug related to java version installed in Windows 10???
I meant, what is the recommendation for java version in Flutter?
Probably they use the old version of java???

**Comment by Tom3652** [comment]
```
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.5/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.5/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.4.5/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.4/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.4/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.5/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Adding ```firebase_messaging``` to the above list and the latest versions of the plugin, even if you are probably already aware of this.
