### ISSUE TITLE
[firebase auth] FirebaseUser.reauthenticateWithCredential finished with NoSuchMethodError exception

### ISSUE THREAD

**Issue by hungnt-kayac** [FirebaseExtended/flutterfire#76]
plugin version: 
```
firebase_core: ^0.4.0+9
firebase_auth: ^0.14.0+5
```
here is the screenshot
<img width="1399" alt="Screen Shot 2019-09-02 at 19 58 26" src="https://user-images.githubusercontent.com/18458688/64110070-12889f00-cdbc-11e9-9d26-51cd538107dd.png">

**Comment by hungnt-kayac** [comment]
@BondarenkoStas 
i created a sample app here
https://github.com/nguyentuanhung/flutter_firebase_sample
(for some reason, i don't push the whole flutter project, just `lib` folder and `pubspec.yaml` file)

In this example, i login via email, password and then try to reauthenticate with provided email and password

**Comment by fabryx92** [comment]
I have the same problem. But my situation is different.
I have an anonymous user that should be converted to an "email and password" one. By using linkWithCredential() and reauthenticateWithCredential() i encounter the same error as hungnt-kayac

**Comment by alexZaicev** [comment]
I experience the same problem, when I try to re-authenticate user it throw exception: 

`NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("user")`

**Comment by pawlowskim** [comment]
Same here.


```
  Future<AuthResult> reAuthenticate(String email, String password) {
    return getFirebaseUser().then((FirebaseUser user) {
      AuthCredential credential =
          EmailAuthProvider.getCredential(email: email, password: password);
      return user.reauthenticateWithCredential(credential);
    });
  }
```
If password is correct it throws:
```
I/flutter (14968): Error: NoSuchMethodError: The method '[]' was called on null
I/flutter (14968): Receiver: null
I/flutter (14968): Tried calling: []("user")
```

If password is incorrect it returns error (expected):
```
flutter: PlatformException(ERROR_WRONG_PASSWORD, The password is invalid or the user does not have a password., null)
```

**Comment by fabryx92** [comment]
@pawlowskim I've done a PR (https://github.com/FirebaseExtended/flutterfire/pull/237) that should fix this error. I'm waiting for the code review.

**Comment by feinstein** [comment]
I am still getting the NoSuchMethodError: The method '[]' was called on null., even after updating to version 0.15.0 and running pub get.

**Comment by fabryx92** [comment]
@feinstein have you tried a `flutter clean`?

**Comment by feinstein** [comment]
@fabryx92 no I didn't, but I expected pub to respect the minimum version and, pubspec.lock has the right version, but I will give it a try and let you know.

**Comment by feinstein** [comment]
I did a `flutter clean` > `flutter get` > `flutter upgrade` > Stopped and Restarted the App > Confirmed pubspec.lock has firebase_auth 0.15.0+1 and it worked, thanks @fabryx92

**Comment by fabryx92** [comment]
@feinstein awesome! I think a previous version of the package was cached, sometimes this happens even after doing `pub get`.
