### ISSUE TITLE
🐛 [  firebase_core: ^1.5.0   cloud_firestore: ^3.1.7] Bug Causing Tremendous READS

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [FirebaseExtended/flutterfire#8127]
## Bug report

**Describe the bug**
even if I do write operations let alone read operations the READ counts goes insane

I made a fresh new flutter project and fresh new firebase account so I can monitor from 0 
the whole flutter project had 1 global variable (final fireStoreGlobal = FirebaseFirestore.instance; ) 1 button and that 1 button performed the following function which is a loop to add 200 documents each document with 3 fields 

the widget/function was 

### Center(
  child: ElevatedButton(
      onPressed: () async {
        for (int i = 0; i < 201; i++) {
          String uiD = Uuid().v1();

          fireStoreGlobal.collection('DemoList').doc(uiD).set({
            'Link': 'Link',
            'Description': 'Description',
            'Name': 'Name'
          });
        }
      },
      child: Text('Add')),
),

then I waited an hour and then I went to usage and saw TODAYS usage and it said 200 writes ( that works fine since 200 documents were added ) but then it said **1.2k READS**!!! where did these **READS** come from? 

### Steps to reproduce

1. Create a fresh new firebase project / use a project that isn't use so you can accurately monitor todays usage
2. Create a fresh new flutter project / use a project that does not have perform anyother write read other than the button 
3. Create a button with the following ontap function   onPressed: () async {
        for (int i = 0; i < 201; i++) {
          String uiD = Uuid().v1();

          fireStoreGlobal.collection('DemoList').doc(uiD).set({
            'Link': 'Link',
            'Description': 'Description',
            'Name': 'Name'
          });
        }
4. See your usage  see after an hour or so because the usage comes in gradually not all at once

### Expected behavior

For that loop function only 200 Writes should be made. 0 deletes. 0 reads 

and if I call all those 200 documents then only 200 documents reads not 200*3

### Sample project

NIL

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.0.6 at /Users/farhan/Developer/flutter
    • Framework revision 1d9032c7e1 (10 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/farhan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.



     Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the webde.app/Contents/Developer
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • A0C128D8-E098-412A-8A5B-A7248B6147AE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.102


• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^1.5.0
  cloud_firestore: ^3.1.7
  uuid: ^3.0.5

```

</details>

---

**Comment by darshankawar** [comment]
@officialFlutterDeveloper 
You are on older version of flutter. Current stable is 2.10.2. So please upgrade your version to latest and all firebase plugins you are using to the latest and try again to see if you still see the same behavior or not.

**Comment by darshankawar** [comment]
@officialFlutterDeveloper 
I am unable to replicate the behavior you are reporting using latest stable and plugin versions you used. 
Can you provide the log you see when it spawns the console ?

**Comment by officialFlutterDeveloper** [comment]
@darshankawar you were not able to replicate it and neither was I  just now because firebase fixed this bug ( I also had mailed firebase official support ) but unfortunately I did not get any credit for pointing out this such high level bug which only got fixed because of my reporting or this issue has persisted for long time

**Comment by darshankawar** [comment]
Thanks for the update and glad to know the issue is now resolved at your end.
Closing this.

**Comment by officialFlutterDeveloper** [comment]
Still not fully fixed just found out when you get the documents instead of getting 200 or 201 I got 800
<img width="923" alt="Screenshot 2022-03-12 at 15 42 40" src="https://user-images.githubusercontent.com/82877513/158014925-7a7a69af-22c2-4f76-8695-85e02d2ab422.png">
