### ISSUE TITLE
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

### ISSUE THREAD

**Issue by SnowStar0423** [FirebaseExtended/flutterfire#8254]
I have got a new issue in android 12

Error: ADB exited with exit code 1
Performing Streamed Install

```
adb: failed to install D:\Work\Flutter\I_refer_deals_Rajesh\ireferdeals_user\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl388963428.tmp/base.apk (at Binary XML file line #193): io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on sdk gphone64 x86 64.
```

![image](https://user-images.githubusercontent.com/61679921/157670823-5a38b86d-66ad-4b0a-9ed2-de22e1b4cd95.png)

**Comment by AguSampietro** [comment]
same error here

**Comment by AguSampietro** [comment]
In your manifest, add `<activity ...  android:exported="true">`

**Comment by SnowStar0423** [comment]
I have already added it my manifest,
Only, when I use this package, I can see this issue.

**Comment by SnowStar0423** [comment]
Are they related with Flutter version which I'm using?

**Comment by darshankawar** [comment]
@SnowStar0423 
This has been fixed recently and should be available on latest master: https://github.com/flutter/flutter/issues/98256#issuecomment-1039419684
So if you are not on latest master, then switch to it, get the latest version and try again.

```
flutter channel master
flutter upgrade
```

**Comment by AnuPrajapati** [comment]
I am also stuck in same  error. As I have upgrade the master  but still getting same error..

**Comment by AguSampietro** [comment]
Things I've done to make it works.

Added this below `dependencies`
dependency_overrides:
  platform: ^3.1.0

then run
`flutter upgrade`

then add
`<activity ... android:exported="true">`

then run 
`flutter clean`
`flutter pub get`
`flutter run`

I'm using this environment
environment:
   sdk: ">=2.12.0 <3.0.0"

**Comment by SnowStar0423** [comment]
Dear AguSampietro,

Thank you for your answer.

My current Flutter SDK version is 1.22.6 in this project.

environment:
    sdk: ">=2.7.0 <3.0.0"

Also, I'm using the following version in dependencies:

firebase_core: ^0.5.0+1
firebase_messaging: ^7.0.3

I was trying to fix this error through above methods, but  I couldn't find the perfect solution in the current version.

If I upgrade these packages' version with the latest Flutter SDK version, will this issue be solved easily?

Please let me know about that kindly if you have had  like this  experience before.

Thank you.

**Comment by darshankawar** [comment]
> My current Flutter SDK version is 1.22.6 in this project.
> 
> environment: sdk: ">=2.7.0 <3.0.0"
> 
> Also, I'm using the following version in dependencies:
> 
> firebase_core: ^0.5.0+1 firebase_messaging: ^7.0.3

You are on obsolete version of Flutter and the plugin versions too are very old. You'll need to upgrade wherein you'll get to see the fix as I mentioned earlier. The fix made is not available on the version you are on.

I am going ahead and closing this as there are solutions mentioned above that you can try. If you disagree, write in comments and I'll reopen it.

**Comment by SnowStar0423** [comment]
Thank you for your answering.

After I upgrade the current version into the latest version with Flutter SDK Version, if it doesn't solve, I will contact you again.
