### ISSUE TITLE
[Firebase Analytics] setAnalyticsCollectionEnabled(false) has no effect on iOS

### ISSUE THREAD

**Issue by ToniTornado** [FirebaseExtended/flutterfire#90]
**Describe the bug**
`FirebaseAnalytics().setAnalyticsCollectionEnabled(false);` does not deactivate data collection on iOS.

**To Reproduce**
Call setAnalyticsCollectionEnabled(false) on your instance of FirebaseAnalytics. The Xcode log prints `[Firebase/Analytics][I-ACS023012] Analytics enabled`. All events are transmitted to the Firebase console.

**Expected behavior**
Transmission of events stops.

**Additional context**
The platform channel invokes the native iOS method in FirebaseAnalyticsPlugin.m:
```
} else if ([@"setAnalyticsCollectionEnabled" isEqualToString:call.method]) {
  NSNumber *enabled = [NSNumber numberWithBool:call.arguments];
  [FIRAnalytics setAnalyticsCollectionEnabled:[enabled boolValue]];
  result(nil);
}
```
`call.arguments` is of type `__NSCFBoolean` and the subsequent lines always convert the value that is passed to FIRAnalytics to `true`.

Add this code to the else if:
```
if ((int)call.arguments == 279097312) { // if passed false: 279097336
  NSLog(@"TRUE ARGUMENT WILL SET COLLECTION TO %@", [[NSNumber numberWithBool:call.arguments] boolValue] ? @"TRUE" : @"FALSE");
} else {
  NSLog(@"FALSE ARGUMENT WILL SET COLLECTION TO %@", [[NSNumber numberWithBool:call.arguments] boolValue] ? @"TRUE" : @"FALSE");
}
```
It prints
`Runner[8875:2258309] TRUE ARGUMENT WILL SET COLLECTION TO TRUE`
or
`Runner[8875:2258309] FALSE ARGUMENT WILL SET COLLECTION TO TRUE`.

**Comment by ToniTornado** [comment]
```
flutter --version
Flutter 1.8.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e4ebcdf6f4 (6 weeks ago) • 2019-07-27 11:48:24 -0700
Engine • revision 38ac5f30a7
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)
```

**Comment by ToniTornado** [comment]
This code works:
```
} else if ([@"setAnalyticsCollectionEnabled" isEqualToString:call.method]) {
  [FIRAnalytics setAnalyticsCollectionEnabled:[call.arguments boolValue]];
  result(nil);
}
```
I just skipped the first conversion step.

**Comment by kroikie** [comment]
@ToniTornado would you be willing to produce a PR with that change? Seems to be a pretty quick fix.

**Comment by ToniTornado** [comment]
@kroikie Yes it is a quick fix but I'm not sure about any implications? 

There are similar code fragments for InAppMessaging (that I'm not using) in FirebaseInAppMessagingPlugin.m:
```
} else if ([@"setMessagesSuppressed" isEqualToString:call.method]) {
  NSNumber *suppress = [NSNumber numberWithBool:call.arguments];
  FIRInAppMessaging *fiam = [FIRInAppMessaging inAppMessaging];
  fiam.messageDisplaySuppressed = [suppress boolValue];
  result(nil);
} else if ([@"setAutomaticDataCollectionEnabled" isEqualToString:call.method]) {
  NSNumber *enabled = [NSNumber numberWithBool:call.arguments];
  FIRInAppMessaging *fiam = [FIRInAppMessaging inAppMessaging];
  fiam.automaticDataCollectionEnabled = [enabled boolValue];
  result(nil);
}
```
I changed these lines too.

**Comment by ToniTornado** [comment]
The main bug has now been fixed in master v5.0.2. But I still recommend to fix the other plugin too. I updated my PR.

**Comment by moroumo** [comment]
still see the analytics reports the "first_open" event when the flag is set as "false" in debug mode with iOS simulator. but doesn't report other events if the app is opened once.
```
  firebase_core: ^0.4.0+6
  firebase_crashlytics: ^0.1.0+3
  firebase_analytics: ^5.0.2
```
```
class GrowSState extends State<GrowS> {
FirebaseAnalytics analytics = FirebaseAnalytics();

  @override
  void initState() {
    super.initState();

    if (sys_utils.buildMode == sys_utils.BuildMode.release) {
      analytics.setAnalyticsCollectionEnabled(true);
    } else {
      analytics.setAnalyticsCollectionEnabled(false);
    }
  }
````

![Screen Shot 2019-10-16 at 21 49 36](https://user-images.githubusercontent.com/1180670/66978491-005a7b80-f05f-11e9-9b21-f532ee45d1b9.png)

**Comment by kroikie** [comment]
@moroumo `setAnalyticsCollectionEnabled` is meant to update the analytics collection mode of the app. If analytics is enabled before `setAnalyticsCollectionEnabled` is used to disable analytics events will be logged till execution of `setAnalyticsCollectionEnabled` is complete.

To see how to configure the initial state of analytics collection see the [docs](https://firebase.google.com/docs/analytics/configure-data-collection)

@ToniTornado I'm closing this issue, `setAnalyticsCollectionEnabled` now works on iOS.
